title: Flux Cheat Sheet
description: Cheat sheet of commands for using Flux
author: vsoch
baseurl: "/cheat-sheet"
url: ""
keywords: hpc, flux, flux-framework
lang: en-US
timezone:  America/Denver
repo: https://github.com/flux-framework/cheat-sheet

# Social Profiles
twitter_username:  FluxFramework
github_username:   flux-framework
logo: assets/images/logo.png


collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:title/

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"


# Build settings
exclude: ["_site", "vendor", ".github"]

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
    
exclude:
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor

relative_links:
  enabled:     true
  collections: false
