name: flux cheat sheet validate

on:
  pull_request: []

jobs:
  validate-commands:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Validate Commands Data
      run: |
        sudo apt-get update && sudo apt-get install -y python3 python3-pip python3-setuptools wget
        sudo pip3 install -r .github/scripts/requirements.txt
        python3 .github/scripts/validate.py
